services:
  browserquest:
    build: .
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/health || exit 1"]
      interval: 10s
      retries: 3
    networks:
      - lan

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./deploy/nginx/browserquest.conf:/etc/nginx/conf.d/browserquest.conf:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - browserquest
    networks:
      - lan

networks:
  lan:
    driver: bridge
